jwt:
    secretKey: 3c6e0b8a9c15224a8228b9a98ca1531d
    expiration: 86400000
spring:
  application:
    name: Ecommerce-Api-Gateway
  cloud:
    gateway:
      routes:
        - id: Ecommerce-product
          uri: lb://ECOMMERCE-PRODUCT
          predicates:
            - Path=/api/v1/products/**
          filters:
            - StripPrefix=2
        - id: Ecommerce-user
          uri: lb://ECOMMERCE-USER
          predicates:
            - Path=/api/v1/users/**
          filters:
            - StripPrefix=2
            - name: LoggingSpecificRouteFilter
            - name: AuthenticationFilter
              args:
                isEnabled: true
            - name:  AuthorizationFilter
              args:
                allowedRoles: ADMIN,SUPER_ADMIN
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
server:
  port: 8000
